language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - pip install pep8 --use-mirrors
    - pip install pyflakes --use-mirrors
script:
    - pep8 daemons/
    - pyflakes daemons/
    - py.test tests/
