language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - pip install pycodestyle
    # Install a legacy pyflakes to use with Python2.6 since they no longer
    # support installing the project in Python2.6 environments after 2.0.0.
    # We should be able to use any modern version of pyflakes for modern Python
    # installations.
    - if [[ "$(python --version 2>&1)" =~ Python\ 2\.6.* ]]; then pip install pyflakes==1.6.0; else pip install pyflakes; fi
    # Similarly, pytest has dropped support for Python 2.6 and 3.2. This
    # installs a legacy version of it for those cases.
    - if [[ "$(python --version 2>&1)" =~ Python\ (3\.2.*|2\.6.*) ]]; then pip install "pytest<3.0.0"; else pip install pytest; fi
    - pip install -e ./
script:
    - pycodestyle daemons/
    - pycodestyle tests/
    - pyflakes daemons/
    - pyflakes tests/
    - py.test tests/
