language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - pip install pep8
    - pip install pyflakes
    - pip install -e ./
script:
    - pep8 daemons/
    - pep8 tests/
    - pyflakes daemons/
    - pyflakes tests/
    - py.test tests/
